// MOD-02 egress control for the `front` service (technical-design §1, review R3-01, R4-01).
// Generated from config.egressHosts: one nginx `server` per allowed host, plus the host list the
// front entrypoint issues its certificate for. The Keystone server allows only the paths of the
// chosen connections (egress-identity.ts).
// - hosts.txt is fixed for a checkout: it is committed and baked into the front image.
// - servers.conf depends on the Keystone set chosen at runtime, so the bridge writes it into its
//   home (<home>/front/servers.conf) before each start; compose mounts that folder read-only into
//   front. Its hash is a front label, so a running front with another set is never reused.
//
// Why not a CONNECT proxy (R3-01): a CONNECT allowlist checks only the tunnel target. After
// CONNECT the box owns the TLS session, so on a shared front door (Cloudflare anycast, Azure
// Container Apps) it could pick any SNI or Host and reach any site behind the same IP. `front`
// ends the box's TLS itself (internal CA) and opens its own verified TLS session to ONE fixed
// upstream per server, with SNI and Host forced to that name. The box never picks the upstream.
// - An SNI that names no allowed host fails the handshake (default server, ssl_reject_handshake).
// - A Host header that differs from the SNI's server gets 421 and is never sent upstream.
//
// Package registries are deliberately NOT allowed here (review N3): the box reaches npm/PyPI only
// through the read-only caches (docker/caches).
//
// Regenerate the committed hosts.txt: bun src/guard/egress.ts
import { createHash } from "node:crypto"
import { writeFileSync } from "node:fs"
import path from "node:path"
import { defaultConfig, type BridgeConfig } from "../shared/config.ts"
import { SYNAPSE_HOST } from "../synapse/auth-conf.ts"
import { synapseLocations } from "../synapse/front-routes.ts"
import { DYNAMIC_ID } from "../shared/keystone.ts"
import { identityLocations } from "./egress-identity.ts"

// Lower-case DNS name, at least two labels, no wildcard, port, scheme, quote, space or brace.
const HOSTNAME = /^(?!-)[a-z0-9-]{1,63}(?<!-)(\.(?!-)[a-z0-9-]{1,63}(?<!-))+$/
/** A label that makes the name an IP literal or IP-like (WHATWG parses a numeric last label as IPv4). */
const NUMERIC_LABEL = /^(\d+|0x[0-9a-f]*)$/

/** The only port the box reaches the allowed hosts on (front listens there; upstream is 443 too). */
export const EGRESS_PORT = 443
/** The committed host list, relative to docker/. */
export const FRONT_HOSTS_FILE = "front/hosts.txt"
/** The generated servers file, inside the bridge's front folder (config.frontDir). */
export const FRONT_SERVERS_NAME = "servers.conf"
/** Where front reads the generated folder (compose.yaml mounts it read-only; nginx.conf includes it). */
export const FRONT_GENERATED_MOUNT = "/etc/nginx/front-gen"
const HEADER = "# Generated by src/guard/egress.ts from config.egressHosts. Do not edit."
const SERVERS_HEADER = "# Generated by the bridge (src/guard/egress.ts) from config.egressHosts and the chosen Keystone connections. Do not edit."

/** The Keystone host whose paths are limited, and the chosen connection ids. */
export type FrontKeystone = { host: string; connections: readonly string[] }

/** Hosts whose presence would reopen the publish/exfiltration route N3 closed. */
export const REGISTRY_HOSTS = new Set([
  "registry.npmjs.org",
  "registry.npmjs.com",
  "registry.yarnpkg.com",
  "npm.pkg.github.com",
  "pypi.org",
  "upload.pypi.org",
  "test.pypi.org",
  "files.pythonhosted.org",
])

function isIpLiteral(host: string): boolean {
  if (host.includes(":") || host.startsWith("[")) return true // IPv6, bracketed or not
  const labels = host.split(".")
  return labels.some((label) => /^\d+$/.test(label)) || NUMERIC_LABEL.test(labels[labels.length - 1] ?? "")
}

function normalise(host: string): string {
  const lower = host.toLowerCase()
  if (isIpLiteral(lower)) throw new Error(`egress host ${JSON.stringify(host)} is an IP literal; list DNS names only`)
  if (!HOSTNAME.test(lower)) throw new Error(`egress host ${JSON.stringify(host)} is not a plain DNS name`)
  if (REGISTRY_HOSTS.has(lower)) throw new Error(`egress host ${lower} is a package registry; use the caches (review N3)`)
  return lower
}

/** The allowed hosts, lower-cased and de-duplicated. Throws on anything that is not a plain host name. */
export function egressHostList(hosts: readonly string[]): string[] {
  const unique = [...new Set(hosts.map(normalise))]
  if (unique.length === 0) throw new Error("egress host list is empty; refusing to generate (would hide a config error)")
  return unique
}

/** The whole-host location of a non-Keystone, non-Synapse server. */
function wholeHost(host: string): string[] {
  return [
    "    location / {",
    "        # A variable makes nginx resolve at run time with the resolver (front's own aliases would loop).",
    `        set $front_upstream "${host}";`,
    "        proxy_pass https://$front_upstream;",
    `        proxy_ssl_name ${host};`,
    `        proxy_set_header Host ${host};`,
    "        include /etc/nginx/front/upstream.conf;",
    "    }",
  ]
}

/** One fixed-upstream server. `host` is already validated, so it is safe inside the quotes. */
function server(host: string, locations: string[]): string[] {
  return [
    "server {",
    `    listen ${EGRESS_PORT} ssl;`,
    `    server_name ${host};`,
    "    ssl_certificate /tmp/front/leaf.pem;",
    "    ssl_certificate_key /tmp/front/leaf.key;",
    "    # nginx picks the TLS server by SNI but the request server by Host, so both are checked.",
    `    if ($ssl_server_name != "${host}") { return 421; }`,
    `    if ($host != "${host}") { return 421; }`,
    ...locations,
    "}",
  ]
}

/**
 * The nginx servers for `hosts`: a default server that refuses, then one fixed upstream per host.
 * The Keystone host (keystone.host, which must be one of `hosts`) gets only the chosen connections' paths.
 */
export function frontServers(hosts: readonly string[], keystone: FrontKeystone): string {
  const list = egressHostList(hosts)
  const identity = keystone.host.toLowerCase()
  if (!list.includes(identity)) throw new Error(`the Keystone host ${JSON.stringify(keystone.host)} is not an egress host`)
  const defaultServer = [
    "# An SNI that names no allowed host (or no SNI) fails the TLS handshake.",
    "# A request that reaches it anyway (Host naming no allowed host) gets 421.",
    "server {",
    `    listen ${EGRESS_PORT} ssl default_server;`,
    "    ssl_reject_handshake on;",
    "    return 421;",
    "}",
  ]
  const servers = list.flatMap((host) => ["", ...server(host, host === identity ? identityLocations(host, keystone.connections) : host === SYNAPSE_HOST ? synapseLocations(host, FRONT_GENERATED_MOUNT) : wholeHost(host))])
  return [SERVERS_HEADER, ...defaultServer, ...servers, ""].join("\n")
}

/**
 * frontServers for a config whose keystoneConnections is already the effective set (effectiveConfig).
 * #104: with the dynamic connection chosen, the delegation profile's digest is written as a comment,
 * so the front-config label (the file's sha256) changes with the profile and a running set with
 * another profile is never reused (the gate reads the profile only when it starts).
 */
export function frontServersFor(config: Pick<BridgeConfig, "egressHosts" | "keystoneOrigin" | "keystoneConnections" | "dynamicProfile">): string {
  const servers = frontServers(config.egressHosts, { host: new URL(config.keystoneOrigin).hostname, connections: config.keystoneConnections })
  if (!config.keystoneConnections.includes(DYNAMIC_ID)) return servers
  return `${servers}# delegation profile sha256: ${createHash("sha256").update(config.dynamicProfile).digest("hex")}\n`
}

/** The front-config label value: sha256 of the generated servers file. */
export const frontConfigHash = (servers: string) => createHash("sha256").update(servers).digest("hex")

/** The host list the front entrypoint issues its leaf certificate (and CA name constraints) for. */
export function frontHosts(hosts: readonly string[]): string {
  return [HEADER, ...egressHostList(hosts), ""].join("\n")
}

if (import.meta.main) {
  const file = path.join(import.meta.dir, "..", "..", "docker", FRONT_HOSTS_FILE)
  writeFileSync(file, frontHosts(defaultConfig({}).egressHosts))
  process.stderr.write(`wrote ${file}\n`)
}
