// MOD-02 egress allowlist for the tinyproxy `egress` service (technical-design §1).
// Generated from config.egressHosts: one anchored POSIX ERE per host, dots escaped.
// tinyproxy runs with FilterDefaultDeny, so anything not listed is refused.
//
// CONNECT only (review C-5). tinyproxy.conf sets `FilterURLs On`, so each line is matched
// against the request URL, not the bare host. For a CONNECT tunnel that URL is the request
// target `host:443`; for a plain-HTTP proxy request it is `http://host/...`. Every line is
// `^<host>:443$`, so plain HTTP never matches — not even to an allowed host — and is refused
// (403). tinyproxy 1.11 has no "CONNECT only" switch; this anchored URL filter is how it is
// enforced. Proven live: test/egress-live.test.ts (OCD_LIVE_EGRESS=1).
//
// Package registries are deliberately NOT allowed here (review N3): the box reaches npm/PyPI only
// through the read-only caches (docker/caches). tinyproxy filters by host, not by client, so a
// registry host on this list would give the box a direct route to the publish endpoints.
//
// Regenerate the committed default: bun src/guard/egress.ts
import { writeFileSync } from "node:fs"
import path from "node:path"
import { defaultConfig } from "../shared/config.ts"

// Lower-case DNS name, at least two labels, no wildcard, port, scheme or regex syntax.
const HOSTNAME = /^(?!-)[a-z0-9-]{1,63}(?<!-)(\.(?!-)[a-z0-9-]{1,63}(?<!-))+$/
/** A label that makes the name an IP literal or IP-like (WHATWG parses a numeric last label as IPv4). */
const NUMERIC_LABEL = /^(\d+|0x[0-9a-f]*)$/

/** The only port the proxy tunnels to (tinyproxy.conf `ConnectPort 443`). */
export const EGRESS_PORT = 443

/** Hosts whose presence would reopen the publish/exfiltration route N3 closed. */
export const REGISTRY_HOSTS = new Set([
  "registry.npmjs.org",
  "registry.npmjs.com",
  "registry.yarnpkg.com",
  "npm.pkg.github.com",
  "pypi.org",
  "upload.pypi.org",
  "test.pypi.org",
  "files.pythonhosted.org",
])

function isIpLiteral(host: string): boolean {
  if (host.includes(":") || host.startsWith("[")) return true // IPv6, bracketed or not
  const labels = host.split(".")
  return labels.some((label) => /^\d+$/.test(label)) || NUMERIC_LABEL.test(labels[labels.length - 1] ?? "")
}

function normalise(host: string): string {
  const lower = host.toLowerCase()
  if (isIpLiteral(lower)) throw new Error(`egress host ${JSON.stringify(host)} is an IP literal; list DNS names only`)
  if (!HOSTNAME.test(lower)) throw new Error(`egress host ${JSON.stringify(host)} is not a plain DNS name`)
  if (REGISTRY_HOSTS.has(lower)) throw new Error(`egress host ${lower} is a package registry; use the caches (review N3)`)
  return lower
}

/** The tinyproxy Filter file for `hosts`. Throws on anything that is not a plain host name. */
export function egressAllowlist(hosts: readonly string[]): string {
  const unique = [...new Set(hosts.map(normalise))]
  if (unique.length === 0) throw new Error("egress allowlist is empty; refusing to generate (would hide a config error)")
  const lines = unique.map((host) => `^${host.replaceAll(".", "\\.")}:${EGRESS_PORT}$`)
  return ["# Generated by src/guard/egress.ts from config.egressHosts. Do not edit.", ...lines, ""].join("\n")
}

if (import.meta.main) {
  const target = path.join(import.meta.dir, "..", "..", "docker", "egress", "allow.txt")
  writeFileSync(target, egressAllowlist(defaultConfig({}).egressHosts))
  process.stderr.write(`wrote ${target}\n`)
}
