// Regression proof: a real nginx master is paused while the checked reload runs.
// No external network, ports, credentials, host mounts, or shared containers.
import { readFile } from "node:fs/promises"

const source = await readFile(new URL("../docker/front/front-reload.sh", import.meta.url), "utf8")
const script = `set -eu
mkdir -p /tmp/proof/gen /tmp/proof/run /tmp/proof/bin
cat > /tmp/proof/bin/nginx <<'WRAPPER'
#!/bin/sh
exec /usr/sbin/nginx -c /tmp/proof/nginx.conf "$@"
WRAPPER
chmod +x /tmp/proof/bin/nginx
export PATH=/tmp/proof/bin:$PATH
export OCD_FRONT_GEN=/tmp/proof/gen
export OCD_FRONT_RUN=/tmp/front
cat > /tmp/proof/nginx.conf <<'CONF'
worker_processes 1;
pid /tmp/proof/nginx.pid;
error_log /tmp/proof/errors.log warn;
events { worker_connections 32; }
http {
 access_log off;
 client_body_temp_path /tmp/proof/client;
 proxy_temp_path /tmp/proof/proxy;
 fastcgi_temp_path /tmp/proof/fastcgi;
 uwsgi_temp_path /tmp/proof/uwsgi;
 scgi_temp_path /tmp/proof/scgi;
 include /tmp/front/current.conf;
}
CONF
cat > /tmp/proof/gen/servers.conf <<'SERVERS'
server {
 listen 127.0.0.1:8088;
 location / {
  include /etc/nginx/front-gen/synapse-auth.conf;
  if ($synapse_auth = "") { return 200 "old-config"; }
  return 200 "new-config";
 }
}
SERVERS
export OCD_FRONT_HASH=$(sha256sum /tmp/proof/gen/servers.conf | cut -d' ' -f1)
cp /tmp/proof/gen/servers.conf /tmp/proof/source-backup
cat > /tmp/proof/gen/synapse-auth.conf <<'EMPTY'
# Generated by the bridge (src/synapse/auth-conf.ts). One variable only. Do not edit.
set $synapse_auth "";
EMPTY
cp /tmp/proof/gen/synapse-auth.conf /tmp/proof/empty-backup
cat > /tmp/proof/reload.sh <<'SCRIPT'
${source.replaceAll("\r\n", "\n")}
SCRIPT
sh /tmp/proof/reload.sh --start
/tmp/proof/bin/nginx
master=$(cat /tmp/proof/nginx.pid)
before=$(wget -qO- http://127.0.0.1:8088)
kill -STOP "$master"
while ! grep -Eq '^State:[[:space:]]+T' /proc/$master/status; do sleep 0.01; done
cat > /tmp/proof/gen/synapse-auth.conf <<'FRESH'
# Generated by the bridge (src/synapse/auth-conf.ts). One variable only. Do not edit.
set $synapse_auth "Bearer aaaaaaaaaaaa.bbbbbbbbbbbb.cccccccccccc";
FRESH
expected=$(sha256sum /tmp/proof/gen/synapse-auth.conf | cut -d' ' -f1)
sh /tmp/proof/reload.sh > /tmp/proof/reload.log 2>&1 &
reload_pid=$!
attempt=0
while ! grep -q "$expected" /tmp/front/current.conf && [ "$attempt" -lt 100 ]; do
 sleep 0.05
 attempt=$((attempt+1))
done
sleep 0.5
waiting=false
kill -0 "$reload_pid" 2>/dev/null && waiting=true
actual=$(wget -qO- http://127.0.0.1:8088)
marker=$(wget -qO- http://127.0.0.1:19091/__ocd_generation)
old_marker=true
case "$marker" in *" $OCD_FRONT_HASH $expected") old_marker=false;; esac
# Emulate a host write after a signalling caller released its lock: it must not enter the pending load.
sed 's/new-config/unchecked-source/' /tmp/proof/source-backup > /tmp/proof/gen/servers.conf
cp /tmp/proof/empty-backup /tmp/proof/gen/synapse-auth.conf
kill -CONT "$master"
wait "$reload_pid"
reload_exit=$?
after=$(wget -qO- http://127.0.0.1:8088)
attempt=0
while [ "$after" != new-config ] && [ "$attempt" -lt 20 ]; do
 sleep 0.05
 after=$(wget -qO- http://127.0.0.1:8088)
 attempt=$((attempt+1))
done
printf '{"reloadExit":%s,"waitedForWorker":%s,"markerStayedOldWhilePaused":%s,"before":"%s","servedWhileMasterPaused":"%s","afterSourceChangedAndResume":"%s"}\n' "$reload_exit" "$waiting" "$old_marker" "$before" "$actual" "$after"
[ "$reload_exit" = 0 ] && [ "$waiting" = true ] && [ "$old_marker" = true ] && [ "$actual" = old-config ] && [ "$after" = new-config ]
# A master that never acknowledges within 20 s fails, but its later read is still of checked copies.
cp /tmp/proof/source-backup /tmp/proof/gen/servers.conf
kill -STOP "$master"
while ! grep -Eq '^State:[[:space:]]+T' /proc/$master/status; do sleep 0.01; done
set +e
sh /tmp/proof/reload.sh > /tmp/proof/timeout.log 2>&1
timeout_exit=$?
set -e
timed_out_served=$(wget -qO- http://127.0.0.1:8088)
sed 's/old-config/unchecked-source/' /tmp/proof/source-backup > /tmp/proof/gen/servers.conf
kill -CONT "$master"
attempt=0
late=$(wget -qO- http://127.0.0.1:8088)
while [ "$late" != old-config ] && [ "$attempt" -lt 100 ]; do
 sleep 0.05
 late=$(wget -qO- http://127.0.0.1:8088)
 attempt=$((attempt+1))
done
printf '{"timeoutExit":%s,"servedAfterTimeout":"%s","lateLoadAfterSourceChanged":"%s"}\n' "$timeout_exit" "$timed_out_served" "$late"
[ "$timeout_exit" = 7 ] && [ "$timed_out_served" = new-config ] && [ "$late" = old-config ]
# Even a reload with identical content must await a NEW worker, not match an old worker's hashes.
cp /tmp/proof/source-backup /tmp/proof/gen/servers.conf
kill -STOP "$master"
while ! grep -Eq '^State:[[:space:]]+T' /proc/$master/status; do sleep 0.01; done
sh /tmp/proof/reload.sh > /tmp/proof/same.log 2>&1 &
reload_pid=$!
sleep 0.75
same_waiting=false
kill -0 "$reload_pid" 2>/dev/null && same_waiting=true
kill -CONT "$master"
wait "$reload_pid"
printf '{"identicalContentWaitedForNewWorker":%s}\n' "$same_waiting"
[ "$same_waiting" = true ]
# A caller killed inside the container cannot leave a lock that blocks every later reload.
kill -STOP "$master"
while ! grep -Eq '^State:[[:space:]]+T' /proc/$master/status; do sleep 0.01; done
previous=$(cat /tmp/front/current.conf)
sh /tmp/proof/reload.sh > /tmp/proof/killed.log 2>&1 &
reload_pid=$!
attempt=0
while [ "$(cat /tmp/front/current.conf)" = "$previous" ] && [ "$attempt" -lt 100 ]; do
 sleep 0.05
 attempt=$((attempt+1))
done
[ "$(cat /tmp/front/current.conf)" != "$previous" ]
set +e
sh /tmp/proof/reload.sh > /tmp/proof/contender.log 2>&1
contender_exit=$?
kill -KILL "$reload_pid"
wait "$reload_pid" 2>/dev/null
killed_exit=$?
set -e
kill -CONT "$master"
# A short-lived child may still hold the inherited descriptor until it returns.
attempt=0
retry_exit=8
while [ "$retry_exit" = 8 ] && [ "$attempt" -lt 50 ]; do
 sleep 0.1
 set +e
 sh /tmp/proof/reload.sh > /tmp/proof/retry.log 2>&1
 retry_exit=$?
 set -e
 attempt=$((attempt+1))
done
printf '{"whileOwnerRunning":%s,"killedOwnerExit":%s,"retryAfterOwnerDeath":%s}\\n' "$contender_exit" "$killed_exit" "$retry_exit"
[ "$contender_exit" = 8 ] && [ "$killed_exit" = 137 ] && [ "$retry_exit" = 0 ]
# A staging failure also releases the descriptor, without unlinking another caller's lock file.
cat > /tmp/proof/bin/mktemp <<'FAIL'
#!/bin/sh
exit 1
FAIL
chmod +x /tmp/proof/bin/mktemp
set +e
sh /tmp/proof/reload.sh --start > /tmp/proof/stage-failure.log 2>&1
stage_exit=$?
set -e
rm /tmp/proof/bin/mktemp
lock_kept=false
[ -f /tmp/front/reload.lock ] && lock_kept=true
sh /tmp/proof/reload.sh > /tmp/proof/stage-retry.log 2>&1
printf '{"stageFailureExit":%s,"lockFileKept":%s,"retryAfterStageFailure":0}\\n' "$stage_exit" "$lock_kept"
[ "$stage_exit" = 6 ] && [ "$lock_kept" = true ]
! grep -q rmdir /tmp/proof/stage-failure.log
`

const image = process.env.OCD_RELOAD_PROOF_IMAGE
if (!image) throw new Error("Set OCD_RELOAD_PROOF_IMAGE to the front image to test.")
const run = Bun.spawnSync(["docker", "run", "-d", "--name", "ocd-review-reload", "--network", "none", "--read-only", "--tmpfs", "/tmp:exec", "--entrypoint", "sh", image, "-c", "sleep 120"], { env: { ...process.env, MSYS_NO_PATHCONV: "1" } })
if (run.exitCode !== 0) throw new Error(run.stderr.toString())
const container = run.stdout.toString().trim()
try {
  const result = Bun.spawnSync(["docker", "exec", "-i", container, "sh", "-s"], { stdin: Buffer.from(script), env: { ...process.env, MSYS_NO_PATHCONV: "1" }, timeout: 60_000 })
  process.stdout.write(result.stdout)
  process.stderr.write(result.stderr)
  if (result.exitCode !== 0) throw new Error(`reload proof failed: ${result.exitCode}`)
} finally {
  const removed = Bun.spawnSync(["docker", "rm", "-f", container], { env: { ...process.env, MSYS_NO_PATHCONV: "1" } })
  if (removed.exitCode !== 0) {
    process.stderr.write("test container cleanup failed\n")
    process.exitCode = 1
  }
  if (removed.exitCode === 0) process.stdout.write("isolated test container removed\n")
}
