// WS2 (#48): the owner's delegated Synapse token reaches the model gateway through `front`, never
// through the box. The bridge writes <home>/front/synapse-auth.conf; compose already mounts that
// folder read-only into front (at /etc/nginx/front-gen), and the generated synapse2-api server
// includes the file. It is NOT covered by OCD_FRONT_HASH: it changes on every refresh.
//
// The file can only ever set one nginx variable to "" or to "Bearer <JWT>". The writer refuses any
// other value; front's baked `front-reload` (docker/front/front-reload.sh, review M1) and its
// entrypoint refuse any file of another shape, and oc_doctor checks the copy `nginx -T` shows against
// the same strict shape, so the include cannot be used to change anything else in front. Token values are never logged or returned.
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { renameWithRetry } from "./fs-retry.ts"

/** The model gateway host whose credential front sets. */
export const SYNAPSE_HOST = "synapse2-api.alterspective.com.au"
export const AUTH_FILE_NAME = "synapse-auth.conf"
/** The nginx variable the include sets; the synapse server sends it as `Authorization`. */
export const AUTH_VAR = "$synapse_auth"
const HEADER = "# Generated by the bridge (src/synapse/auth-conf.ts). One variable only. Do not edit."
/** A compact JWS: three base64url parts. Keystone tokens are RS256 JWTs. */
export const JWT_RE = /^[A-Za-z0-9_-]{8,4096}\.[A-Za-z0-9_-]{8,8192}\.[A-Za-z0-9_-]{8,4096}$/
/**
 * Longest token front will carry (review L3): the header line nginx builds stays well inside its
 * buffers, and a live `nginx -t` in front accepted an include with a token of exactly this length.
 */
export const MAX_TOKEN_LENGTH = 3800
export const isTokenShape = (token: string) => token.length <= MAX_TOKEN_LENGTH && JWT_RE.test(token)
/** The whole file, exactly: the header and one `set` with "" or "Bearer <JWT>". */
export const AUTH_CONF_SHAPE = /^# Generated by the bridge \(src\/synapse\/auth-conf\.ts\)\. One variable only\. Do not edit\.\nset \$synapse_auth "(Bearer [A-Za-z0-9_-]{8,4096}\.[A-Za-z0-9_-]{8,8192}\.[A-Za-z0-9_-]{8,4096})?";\n$/

/** The file text for `token` (undefined: no credential, so Synapse answers 401: fail closed). */
export function authConf(token: string | undefined): string {
  if (token !== undefined && !isTokenShape(token)) throw new Error(`the Synapse token is not a compact JWT of at most ${MAX_TOKEN_LENGTH} characters; refusing to write it into front`)
  return `${HEADER}\nset ${AUTH_VAR} "${token === undefined ? "" : `Bearer ${token}`}";\n`
}

export const isAuthConf = (text: string) => text.length <= HEADER.length + MAX_TOKEN_LENGTH + 40 && AUTH_CONF_SHAPE.test(text)
/** True when the file carries a token (never the token itself). */
export const authConfHasToken = (text: string) => isAuthConf(text) && text.includes('"Bearer ')

export const authConfPath = (frontDir: string) => path.join(frontDir, AUTH_FILE_NAME)

/** Write then rename (front never reads half a file); 0600 where the OS honours it. */
export async function writeAuthConf(frontDir: string, token: string | undefined): Promise<void> {
  const text = authConf(token)
  await mkdir(frontDir, { recursive: true })
  const file = authConfPath(frontDir)
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`
  await writeFile(tmp, text, { encoding: "utf8", mode: 0o600 })
  await chmod(tmp, 0o600).catch(() => undefined)
  await renameWithRetry(tmp, file)
}

/**
 * Before `compose up`: front's include must exist. Review L5: a missing file is CREATED only (`wx`),
 * so a sign-in that writes the token at the same moment is never overwritten; a file that cannot be
 * read right now (a rename in flight) is left alone. Only a file read as malformed becomes the empty
 * one (fail closed: at worst that removes a token, which the next refresh tick writes again).
 */
export async function ensureAuthConf(frontDir: string): Promise<void> {
  await mkdir(frontDir, { recursive: true })
  const created = await writeFile(authConfPath(frontDir), authConf(undefined), { encoding: "utf8", mode: 0o600, flag: "wx" }).then(
    () => true,
    (error: unknown) => {
      if ((error as NodeJS.ErrnoException).code === "EEXIST") return false
      throw error
    },
  )
  if (created) return
  const text = await readFile(authConfPath(frontDir), "utf8").catch(() => undefined)
  if (text === undefined || isAuthConf(text)) return
  await writeAuthConf(frontDir, undefined)
}
