// WS2 (#48): the owner's delegated Synapse token reaches the model gateway through `front`, never
// through the box. The bridge writes <home>/front/synapse-auth.conf; compose already mounts that
// folder read-only into front (at /etc/nginx/front-gen), and the generated synapse2-api server
// includes the file. It is NOT covered by OCD_FRONT_HASH: it changes on every refresh.
//
// #67 step 3: behind OCD_KEYSTONE_HOST_AUTH, the same folder also holds one ks-auth-<id>.conf per
// chosen Keystone connection, setting $ks_auth. Each generated /mcp/c/<id> location includes only
// its own file, so one connection's token never reaches another connection's path.
//
// Each file can only ever set its one nginx variable to "" or to "Bearer <JWT>". The writer refuses
// any other value; front's baked `front-reload` (docker/front/front-reload.sh, review M1) and its
// entrypoint refuse any file of another shape, and oc_doctor checks the copy `nginx -T` shows against
// the same strict shape, so the include cannot be used to change anything else in front. Token values are never logged or returned.
import { chmod, mkdir, readFile, readdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { CONNECTION_ID } from "../shared/keystone.ts"
import { renameWithRetry } from "./fs-retry.ts"

/** The model gateway host whose credential front sets. */
export const SYNAPSE_HOST = "synapse2-api.alterspective.com.au"
export const AUTH_FILE_NAME = "synapse-auth.conf"
/** The nginx variable the include sets; the synapse server sends it as `Authorization`. */
export const AUTH_VAR = "$synapse_auth"
/** The nginx variable a Keystone connection's include sets (#67 step 3); its /mcp/c/<id> location sends it. */
export const KS_AUTH_VAR = "$ks_auth"
/** The only variables an include may set. A closed set: never a caller-chosen name. */
export type AuthVar = typeof AUTH_VAR | typeof KS_AUTH_VAR
const HEADER = "# Generated by the bridge (src/synapse/auth-conf.ts). One variable only. Do not edit."
/** A compact JWS: three base64url parts. Keystone tokens are RS256 JWTs. */
export const JWT_RE = /^[A-Za-z0-9_-]{8,4096}\.[A-Za-z0-9_-]{8,8192}\.[A-Za-z0-9_-]{8,4096}$/
/**
 * Longest token front will carry (review L3): the header line nginx builds stays well inside its
 * buffers, and a live `nginx -t` in front accepted an include with a token of exactly this length.
 */
export const MAX_TOKEN_LENGTH = 3800
export const isTokenShape = (token: string) => token.length <= MAX_TOKEN_LENGTH && JWT_RE.test(token)
/** The whole file, exactly: the header and one `set` with "" or "Bearer <JWT>". */
export const AUTH_CONF_SHAPE = /^# Generated by the bridge \(src\/synapse\/auth-conf\.ts\)\. One variable only\. Do not edit\.\nset \$synapse_auth "(Bearer [A-Za-z0-9_-]{8,4096}\.[A-Za-z0-9_-]{8,8192}\.[A-Za-z0-9_-]{8,4096})?";\n$/
/** The same shape for a Keystone connection's include: only the variable differs. */
export const KS_AUTH_CONF_SHAPE = /^# Generated by the bridge \(src\/synapse\/auth-conf\.ts\)\. One variable only\. Do not edit\.\nset \$ks_auth "(Bearer [A-Za-z0-9_-]{8,4096}\.[A-Za-z0-9_-]{8,8192}\.[A-Za-z0-9_-]{8,4096})?";\n$/
const SHAPES: Record<AuthVar, RegExp> = { [AUTH_VAR]: AUTH_CONF_SHAPE, [KS_AUTH_VAR]: KS_AUTH_CONF_SHAPE }
const LABELS: Record<AuthVar, string> = { [AUTH_VAR]: "Synapse", [KS_AUTH_VAR]: "Keystone" }

/** The file text for `token` (undefined: no credential, so the upstream answers 401: fail closed). */
export function authConf(token: string | undefined, variable: AuthVar = AUTH_VAR): string {
  if (token !== undefined && !isTokenShape(token)) throw new Error(`the ${LABELS[variable]} token is not a compact JWT of at most ${MAX_TOKEN_LENGTH} characters; refusing to write it into front`)
  return `${HEADER}\nset ${variable} "${token === undefined ? "" : `Bearer ${token}`}";\n`
}

export const isAuthConf = (text: string, variable: AuthVar = AUTH_VAR) => text.length <= HEADER.length + MAX_TOKEN_LENGTH + 40 && SHAPES[variable].test(text)
/** True when the file carries a token (never the token itself). */
export const authConfHasToken = (text: string, variable: AuthVar = AUTH_VAR) => isAuthConf(text, variable) && text.includes('"Bearer ')

export const authConfPath = (frontDir: string) => path.join(frontDir, AUTH_FILE_NAME)

/** `ks-auth-<id>.conf` for a connection id; throws for an id that is not a CONNECTION_ID (no path tricks). */
export function ksAuthFileName(id: string): string {
  if (!CONNECTION_ID.test(id)) throw new Error("not a valid Keystone connection id; refusing to name a front include after it")
  return `ks-auth-${id}.conf`
}

export const ksAuthConfPath = (frontDir: string, id: string) => path.join(frontDir, ksAuthFileName(id))

/** Write then rename (front never reads half a file); 0600 where the OS honours it. */
async function writeAtomic(frontDir: string, file: string, text: string): Promise<void> {
  await mkdir(frontDir, { recursive: true })
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`
  await writeFile(tmp, text, { encoding: "utf8", mode: 0o600 })
  await chmod(tmp, 0o600).catch(() => undefined)
  await renameWithRetry(tmp, file)
}

export async function writeAuthConf(frontDir: string, token: string | undefined): Promise<void> {
  await writeAtomic(frontDir, authConfPath(frontDir), authConf(token))
}

/**
 * #67 step 3: the include front sends as `Authorization` on /mcp/c/<id> only (undefined: no
 * credential, Keystone answers 401). The host token manager calls this for each connection.
 */
export async function writeKsAuthConf(frontDir: string, id: string, token: string | undefined): Promise<void> {
  const file = ksAuthConfPath(frontDir, id)
  await writeAtomic(frontDir, file, authConf(token, KS_AUTH_VAR))
}

/**
 * Review L5: a missing file is CREATED only (`wx`), so a sign-in that writes the token at the same
 * moment is never overwritten; a file that cannot be read right now (a rename in flight) is left
 * alone. Only a file read as malformed becomes the empty one (fail closed: at worst that removes a
 * token, which the next refresh tick writes again).
 */
async function ensureFile(frontDir: string, file: string, variable: AuthVar): Promise<void> {
  await mkdir(frontDir, { recursive: true })
  const created = await writeFile(file, authConf(undefined, variable), { encoding: "utf8", mode: 0o600, flag: "wx" }).then(
    () => true,
    (error: unknown) => {
      if ((error as NodeJS.ErrnoException).code === "EEXIST") return false
      throw error
    },
  )
  if (created) return
  const text = await readFile(file, "utf8").catch(() => undefined)
  if (text === undefined || isAuthConf(text, variable)) return
  await writeAtomic(frontDir, file, authConf(undefined, variable))
}

/** Before `compose up`: front's include must exist. */
export async function ensureAuthConf(frontDir: string): Promise<void> {
  await ensureFile(frontDir, authConfPath(frontDir), AUTH_VAR)
}

/**
 * #67 combined review L4: a connection that left the chosen set keeps no bearer on disk. Every
 * ks-auth-<id>.conf whose id is not chosen is rewritten empty (call under the shared lock, before
 * the sandbox start that loads the new set). Returns the ids emptied (ids only, never a token).
 */
export async function emptyUnchosenKsAuthConf(frontDir: string, chosen: readonly string[]): Promise<string[]> {
  let names: string[]
  try {
    names = await readdir(frontDir)
  } catch {
    return []
  }
  const emptied: string[] = []
  for (const name of names) {
    const id = /^ks-auth-([a-z0-9][a-z0-9-]{0,62})\.conf$/.exec(name)?.[1]
    if (id === undefined || chosen.includes(id)) continue
    const file = ksAuthConfPath(frontDir, id)
    let text: string | undefined
    try {
      text = await readFile(file, "utf8")
    } catch {
      text = undefined
    }
    if (text === authConf(undefined, KS_AUTH_VAR)) continue
    await writeAtomic(frontDir, file, authConf(undefined, KS_AUTH_VAR))
    emptied.push(id)
  }
  return emptied
}

/** Before `compose up` with OCD_KEYSTONE_HOST_AUTH: one include per chosen connection, same rules. */
export async function ensureKsAuthConf(frontDir: string, ids: readonly string[]): Promise<void> {
  for (const id of ids) await ensureFile(frontDir, ksAuthConfPath(frontDir, id), KS_AUTH_VAR)
}
