// R3-01 — the egress front config generated from config.egressHosts (technical-design §1).
// R4-01 — the Keystone server's path rules are covered by test/egress-front-paths.test.ts.
// The live red/green proof is test/egress-live.test.ts (OCD_LIVE_EGRESS=1).
import { describe, expect, test } from "bun:test"
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { checkEgress, egressInput, type EgressInput } from "../src/guard/egress-check.ts"
import { egressHostList, frontHosts, frontServers, frontServersFor } from "../src/guard/egress.ts"
import { defaultConfig } from "../src/shared/config.ts"

const DOCKER = path.join(import.meta.dir, "..", "docker")
const HOSTS = ["identity.alterspective.com.au", "synapse2-api.alterspective.com.au"]
const KS = { host: "identity.alterspective.com.au", connections: ["rag-global", "github", "seqlogs"] }
const read = async (...parts: string[]) => (await readFile(path.join(DOCKER, ...parts), "utf8")).replaceAll("\r\n", "\n")

type Server = { body: string; names: string[]; listen: string[] }

/** Top-level `server { ... }` blocks of a generated config (no nested braces beyond location/if). */
function servers(conf: string): Server[] {
  const blocks = [...conf.matchAll(/^server \{\n([\s\S]*?)\n\}$/gm)].map((m) => m[1] ?? "")
  return blocks.map((body) => ({
    body,
    names: [...body.matchAll(/^ {4}server_name ([^;]+);$/gm)].flatMap((m) => (m[1] ?? "").split(" ")),
    listen: [...body.matchAll(/^ {4}listen ([^;]+);$/gm)].map((m) => m[1] ?? ""),
  }))
}

describe("frontServers", () => {
  const conf = frontServers(HOSTS, KS)
  const all = servers(conf)
  const named = all.filter((s) => s.names.length > 0)

  test("one server per allowed host, named exactly, TLS on 443", () => {
    expect(named.map((s) => s.names)).toEqual(HOSTS.map((h) => [h]))
    for (const s of named) expect(s.listen).toEqual(["443 ssl"])
  })

  test("the default server refuses: unknown SNI fails the handshake, any request that lands there gets 421", () => {
    const fallback = all.filter((s) => s.listen.some((l) => l.includes("default_server")))
    expect(fallback).toHaveLength(1)
    expect(fallback[0]!.names).toEqual([])
    expect(fallback[0]!.body).toContain("ssl_reject_handshake on;")
    expect(fallback[0]!.body).toContain("return 421;")
    expect(fallback[0]!.body).not.toContain("proxy_pass")
  })

  test("each server forces one fixed upstream: proxy_pass, SNI and Host all name its own host", () => {
    for (const s of named) {
      const host = s.names[0]!
      expect(s.body).toContain(`set $front_upstream "${host}";`)
      const passes = [...s.body.matchAll(/proxy_pass (\S+);/g)].map((m) => m[1] ?? "")
      // The model gateway: the whole host. Keystone: one literal path per allowed location (R4-01).
      if (host === KS.host) for (const pass of passes) expect(pass).toMatch(/^https:\/\/\$front_upstream\/[a-z0-9./-]+$/)
      else expect(passes).toEqual(["https://$front_upstream"])
      expect(s.body).toContain(`proxy_ssl_name ${host};`)
      expect(s.body).toContain(`proxy_set_header Host ${host};`)
      expect(s.body).toContain("include /etc/nginx/front/upstream.conf;")
      // No other host appears anywhere in this server.
      for (const other of HOSTS.filter((h) => h !== host)) expect(s.body).not.toContain(other)
    }
  })

  test("a Host or SNI that differs from the server name gets 421 before any proxying", () => {
    for (const s of named) {
      const host = s.names[0]!
      const sni = s.body.indexOf(`if ($ssl_server_name != "${host}") { return 421; }`)
      const hostCheck = s.body.indexOf(`if ($host != "${host}") { return 421; }`)
      expect(sni).toBeGreaterThan(0)
      expect(hostCheck).toBeGreaterThan(0)
      expect(Math.max(sni, hostCheck)).toBeLessThan(s.body.indexOf("location "))
    }
  })

  test("generated, do-not-edit headers", () => {
    expect(conf.split("\n")[0]).toBe("# Generated by the bridge (src/guard/egress.ts) from config.egressHosts and the chosen Keystone connections. Do not edit.")
    expect(frontHosts(HOSTS)).toBe(`# Generated by src/guard/egress.ts from config.egressHosts. Do not edit.\n${HOSTS.join("\n")}\n`)
  })

  const invalid: Array<[string, string[]]> = [
    ["empty list", []],
    ["wildcard", ["*.alterspective.com.au"]],
    ["regex characters", ["identity.alterspective.com.au|.*"]],
    ["port", ["identity.alterspective.com.au:443"]],
    ["scheme", ["https://identity.alterspective.com.au"]],
    ["single label", ["localhost"]],
    ["newline (config injection)", ["identity.alterspective.com.au\nlocation / { proxy_pass https://evil.example; }"]],
    ["semicolon (directive injection)", ["identity.alterspective.com.au; proxy_pass https://evil.example"]],
    ["brace", ["identity.alterspective.com.au}"]],
    ["quote", ['identity.alterspective.com.au"']],
    ["dollar (nginx variable)", ["$host"]],
    ["space", ["identity.alterspective.com.au evil.example"]],
    ["trailing dot", ["identity.alterspective.com.au."]],
    ["npm registry (publish route, N3)", ["registry.npmjs.org"]],
    ["PyPI upload (publish route, N3)", ["upload.pypi.org"]],
    ["PyPI (N3)", ["pypi.org"]],
    ["IPv4 literal", ["10.0.0.1"]],
    ["IPv4 with numeric last label", ["example.123"]],
    ["hex last label", ["example.0x7f"]],
    ["all-numeric label", ["163.example.com"]],
    ["IPv6 literal", ["::1"]],
    ["bracketed IPv6", ["[2001:db8::1]"]],
  ]
  for (const [label, hosts] of invalid) {
    test(`refuses ${label}`, () => {
      expect(() => frontServers(hosts, KS)).toThrow()
      expect(() => frontHosts(hosts)).toThrow()
    })
  }

  test("normalises case and drops duplicates", () => {
    expect(egressHostList(["Identity.Alterspective.com.au", "identity.alterspective.com.au"])).toEqual(["identity.alterspective.com.au"])
    expect(frontServers(["Identity.Alterspective.com.au", "identity.alterspective.com.au"], KS)).toBe(frontServers(["identity.alterspective.com.au"], KS))
  })
})

describe("committed front files", () => {
  test("hosts.txt is the generated file for the default config (no drift); servers.conf is not committed or baked in (R4-01)", async () => {
    expect(await read("front", "hosts.txt")).toBe(frontHosts(defaultConfig({}).egressHosts))
    expect(await readFile(path.join(DOCKER, "front", "servers.conf"), "utf8").catch(() => "absent")).toBe("absent")
    const copies = (await read("front", "Dockerfile")).split("\n").filter((line) => line.startsWith("COPY"))
    expect(copies.some((line) => line.includes("servers.conf"))).toBe(false)
  })

  test("compose mounts the bridge's generated front folder READ-ONLY at the path nginx.conf includes, and labels front with its hash", async () => {
    const compose = await read("compose.yaml")
    expect(compose).toContain("      - ${OCD_FRONT_DIR:?OCD_FRONT_DIR is set by the bridge}:/etc/nginx/front-gen:ro\n")
    expect(compose).toContain("      com.alterspective.opencode-delegate.front-config: ${OCD_FRONT_HASH:?OCD_FRONT_HASH is set by the bridge}\n")
    // Only front gets it (the box never sees the generated folder).
    expect(compose.split("\n").filter((line) => line.includes("OCD_FRONT_DIR"))).toHaveLength(1)
  })

  test("upstream.conf: verified TLS with forced SNI, HTTP/1.1, no buffering, long reads (SSE)", async () => {
    const conf = (await read("front", "upstream.conf")).split("\n").filter((l) => l.trim() && !l.startsWith("#"))
    for (const line of [
      "proxy_ssl_server_name on;",
      "proxy_ssl_verify on;",
      "proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;",
      "proxy_http_version 1.1;",
      "proxy_buffering off;",
      "proxy_request_buffering off;",
      "proxy_read_timeout 3600s;",
    ])
      expect(conf).toContain(line)
    expect(conf.some((l) => l.startsWith("proxy_pass") || l.includes("proxy_set_header Host"))).toBe(false)
  })

  test("nginx.conf resolves upstreams with its own resolver and includes only the generated servers", async () => {
    const conf = await read("front", "nginx.conf")
    expect(conf).toContain("include /tmp/front/resolver.conf;")
    expect(conf).toContain("include /etc/nginx/front-gen/servers.conf;")
    expect(conf).not.toMatch(/^\s*(server|proxy_pass|listen)\b/m)
  })

  test("Dockerfile: pinned nginx base, no CONNECT proxy", async () => {
    const dockerfile = await read("front", "Dockerfile")
    expect(dockerfile).toMatch(/^FROM nginxinc\/nginx-unprivileged:\d+\.\d+\.\d+-alpine@sha256:[0-9a-f]{64}$/m)
    const directives = dockerfile.split("\n").filter((line) => !line.startsWith("#")).join("\n")
    expect(directives).not.toMatch(/tinyproxy|squid|privoxy/)
  })

  test("entrypoint: CA key stays in /ca/private, only the certificate is published, name-constrained", async () => {
    const script = await read("front", "entrypoint.sh")
    expect(script).toContain('cp "$PRIV/ca.pem" "$PUB/ca.pem.new"')
    expect(script).not.toMatch(/\$PUB\/[^"\s]*\.key/)
    expect(script).toContain("nameConstraints=critical,")
    expect(script).toContain("basicConstraints=critical,CA:TRUE,pathlen:0")
  })
})

/** A bridge home whose front folder holds the servers file generated for `connections`. */
async function generatedHome(connections = KS.connections): Promise<EgressInput> {
  const home = await mkdtemp(path.join(os.tmpdir(), "ocd-egress-home-"))
  const config = { ...defaultConfig({}), home, keystoneConnections: connections }
  await mkdir(path.join(home, "front"), { recursive: true })
  await writeFile(path.join(home, "front", "servers.conf"), frontServersFor(config))
  return egressInput(config)
}

describe("checkEgress (oc_doctor)", () => {
  test("the committed files and the generated servers file pass for the default config", async () => {
    expect(checkEgress(await generatedHome())).toEqual({
      ok: true, control: "tls-front", source: "configuration", keystoneConnections: KS.connections,
      keystonePaths: [
        "/.well-known/oauth-authorization-server", "/.well-known/openid-configuration", "/api/oauth/register", "/api/oidc/token",
        "/.well-known/oauth-protected-resource/mcp/c/rag-global", "/mcp/c/rag-global",
        "/.well-known/oauth-protected-resource/mcp/c/github", "/mcp/c/github",
        "/.well-known/oauth-protected-resource/mcp/c/seqlogs", "/mcp/c/seqlogs",
      ],
      frontConfigMatches: true, frontMountReadOnly: true, aliasesMatch: true, connectProxy: false, upstreamTlsVerified: true, boxSealed: true, problems: [],
    })
  })

  test("a generated file for another Keystone set, or none at all, fails (R4-01)", async () => {
    const other = await generatedHome(["rag-global"])
    const check = checkEgress({ ...other, keystone: KS })
    expect(check).toMatchObject({ ok: false, frontConfigMatches: false })
    expect(check.problems.join(" ")).toContain("chosen Keystone set")
    expect(checkEgress({ ...other, frontDir: path.join(os.tmpdir(), "ocd-no-front-dir") })).toMatchObject({ ok: false, frontConfigMatches: false })
  })

  test("a different host list fails: generated files and aliases no longer match", async () => {
    const check = checkEgress({ ...(await generatedHome()), hosts: [...HOSTS, "rag.alterspective.com.au"] })
    expect(check).toMatchObject({ ok: false, frontConfigMatches: false, aliasesMatch: false, connectProxy: false })
  })

  test("an invalid host list fails closed", async () => {
    expect(checkEgress({ ...(await generatedHome()), hosts: ["*.alterspective.com.au"] }).ok).toBe(false)
  })

  test("front without the read-only mount fails", async () => {
    const input = await generatedHome()
    const dir = await mkdtemp(path.join(os.tmpdir(), "ocd-egress-mount-"))
    try {
      await cp(DOCKER, dir, { recursive: true, filter: (src) => !src.includes(`${path.sep}box${path.sep}`) })
      await writeFile(path.join(dir, "compose.yaml"), (await read("compose.yaml")).replace("/etc/nginx/front-gen:ro", "/etc/nginx/front-gen"))
      expect(checkEgress(input, dir)).toMatchObject({ ok: false, frontMountReadOnly: false })
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
  })

  test("a CONNECT proxy left in compose (egress service or a box proxy variable) fails, and a missing dir is reported", async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), "ocd-egress-"))
    try {
      await cp(DOCKER, dir, { recursive: true })
      const compose = (await read("compose.yaml")).replace(
        "      XDG_DATA_HOME: /data\n",
        "      XDG_DATA_HOME: /data\n      HTTPS_PROXY: http://egress:8888\n",
      )
      await writeFile(path.join(dir, "compose.yaml"), compose)
      const check = checkEgress(await generatedHome(), dir)
      expect(check).toMatchObject({ ok: false, connectProxy: true, frontConfigMatches: true })
      expect(check.problems.join(" ")).toContain("HTTPS_PROXY")
    } finally {
      await rm(dir, { recursive: true, force: true })
    }
    const missing = checkEgress(await generatedHome(), path.join(os.tmpdir(), "ocd-egress-missing-dir"))
    expect(missing.ok).toBe(false)
    expect(missing.problems.some((p) => p.includes("unreadable"))).toBe(true)
  })
})
