#!/bin/sh
# Copy, then check: nginx only parses immutable front-local generations. Host writes after this
# command returns (including after a timeout) cannot change a configuration already signalled.
# A signal is not an acknowledgement. Only a fresh loopback request served by the requested
# generation proves a worker loaded it. The endpoint returns hashes only, never a credential.
# Exit codes: 3 files changed/invalid; 4 config test failed (the last current.conf is kept);
# 5 signal failed; 6 snapshot failure; 7 acknowledgement timed out; 8 another local reload is
# running; 2 usage.
set -u
umask 077

GEN=${OCD_FRONT_GEN:-/etc/nginx/front-gen}
RUN=${OCD_FRONT_RUN:-/tmp/front}
HEADER='# Generated by the bridge (src/synapse/auth-conf.ts). One variable only. Do not edit.'
MAX_BYTES=3925
LIVE_URL=http://127.0.0.1:19091/__ocd_generation
ACK_SECONDS=${OCD_FRONT_ACK_SECONDS:-20}
case $ACK_SECONDS in '' | *[!0-9]*) ACK_SECONDS=20 ;; esac
PREVIOUS=
# Set only by a run that stages a generation; never taken from the caller's environment.
STAGE=

log() { printf 'front-reload: %s\n' "$*" >&2; }

# The strict two-line include: $1 file, $2 the one variable it may set, $3 its name for messages.
check_auth() {
  file=$1 var=$2 name=$3
  [ -f "$file" ] || { log "$name is missing; not reloading"; return 3; }
  bytes=$(wc -c < "$file" | tr -d ' ')
  [ "$bytes" -le "$MAX_BYTES" ] || { log "$name is longer than the bridge ever writes; not reloading"; return 3; }
  others=$(LC_ALL=C tr -d 'A-Za-z0-9 #()/._$";\n-' < "$file" | wc -c | tr -d ' ')
  [ "$others" = 0 ] || { log "$name has characters the bridge never writes; not reloading"; return 3; }
  newlines=$(wc -l < "$file" | tr -d ' ')
  records=$(awk 'END { print NR }' "$file")
  [ "$newlines" = 2 ] && [ "$records" = 2 ] || { log "$name is not exactly two lines; not reloading"; return 3; }
  [ "$(sed -n 1p "$file")" = "$HEADER" ] || { log "$name header is not the bridge's; not reloading"; return 3; }
  sed -n 2p "$file" | grep -Eqx "set \\\$$var \"(Bearer [A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,})?\";" \
    || { log "$name does not set only \$$var to \"\" or a bearer token; not reloading"; return 3; }
}

check() {
  [ -n "${OCD_FRONT_HASH:-}" ] || { log "OCD_FRONT_HASH is not set; not reloading"; return 3; }
  SERVERS_SHA=$(sha256sum "$SERVERS" 2> /dev/null | cut -d' ' -f1)
  [ "$SERVERS_SHA" = "$OCD_FRONT_HASH" ] || { log "servers.conf is not the file front started with (OCD_FRONT_HASH); not reloading (restart the sandbox through the bridge)"; return 3; }
  check_auth "$AUTH" synapse_auth synapse-auth.conf || return $?
  AUTH_SHA=$(sha256sum "$AUTH" | cut -d' ' -f1)
  check_keystone
}

# #67 step 3 (OCD_KEYSTONE_HOST_AUTH): servers.conf may include one ks-auth-<id>.conf per Keystone
# connection, each setting only $ks_auth. Only the includes servers.conf names are used. Staging
# (STAGE set) copies each from the host folder, or writes the empty one when the host has none yet
# (fail closed: Keystone answers 401), checks it, and lists it with its hash in ks-auth.list; KS_SHA
# is that list's hash. With --check (no STAGE) the host files that exist are checked in place.
# servers.conf naming any other file of the host folder is refused: nginx would read it unchecked.
check_keystone() {
  KS_SHA=
  # The full folder prefix, never the bare name: a connection id may itself contain `front-gen`.
  mentions=$(grep -o '/etc/nginx/front-gen/' "$SERVERS" | wc -l | tr -d ' ')
  known=$(grep -oE 'include /etc/nginx/front-gen/(synapse-auth|ks-auth-[a-z0-9][a-z0-9-]{0,62})\.conf;' "$SERVERS" | wc -l | tr -d ' ')
  [ "$mentions" = "$known" ] || { log "servers.conf names a generated file front-reload does not check; not reloading"; return 3; }
  ids=$(grep -o 'include /etc/nginx/front-gen/ks-auth-[a-z0-9-]*\.conf;' "$SERVERS" | sed 's|^include /etc/nginx/front-gen/ks-auth-\(.*\)\.conf;$|\1|' | LC_ALL=C sort -u)
  [ -n "$ids" ] || return 0
  list=
  for id in $ids; do
    name=ks-auth-$id.conf
    if [ -n "${STAGE:-}" ]; then
      if [ -f "$GEN/$name" ]; then
        cp "$GEN/$name" "$STAGE/$name" || { log "could not copy $name"; return 3; }
      else
        printf '%s\nset $ks_auth "";\n' "$HEADER" > "$STAGE/$name" || return 6
      fi
      target=$STAGE/$name
    else
      target=$GEN/$name
      [ -f "$target" ] || continue
    fi
    check_auth "$target" ks_auth "$name" || return $?
    list="$list$name $(sha256sum "$target" | cut -d' ' -f1)
"
  done
  [ -n "${STAGE:-}" ] || return 0
  printf '%s' "$list" > "$STAGE/ks-auth.list" || return 6
  KS_SHA=$(sha256sum "$STAGE/ks-auth.list" | cut -d' ' -f1)
}

snapshot() {
  cp "$GEN/servers.conf" "$STAGE/source-servers.conf" && cp "$GEN/synapse-auth.conf" "$STAGE/synapse-auth.conf" \
    || { log "could not copy the generated files"; return 3; }
  SERVERS=$STAGE/source-servers.conf
  AUTH=$STAGE/synapse-auth.conf
  check || return $?
  GENERATION=$SERVERS_SHA-$AUTH_SHA${KS_SHA:+-$KS_SHA}
  # Without Keystone includes this is the three-field reply oc_doctor has always parsed.
  REPLY="$SERVERS_SHA $AUTH_SHA${KS_SHA:+ $KS_SHA}"
  DEST=$RUN/generations/$GENERATION
  # Every include names this immutable generation, never a mutable 'current' directory.
  sed -e "s|include /etc/nginx/front-gen/synapse-auth\.conf;|include $DEST/synapse-auth.conf;|g" \
    -e "s|include /etc/nginx/front-gen/\(ks-auth-[a-z0-9-]*\.conf\);|include $DEST/\1;|g" "$SERVERS" > "$STAGE/servers.conf" || return 6
  # Retries reuse the same content-addressed generation. Never overwrite a file nginx may read.
  if [ -d "$DEST" ]; then
    same=yes
    for name in source-servers.conf synapse-auth.conf servers.conf ${KS_SHA:+ks-auth.list} $(cut -d' ' -f1 "$STAGE/ks-auth.list" 2> /dev/null); do
      cmp -s "$STAGE/$name" "$DEST/$name" || same=no
    done
    [ "$same" = yes ] || { log "the existing generation differs from its content hash"; return 6; }
  else
    mv "$STAGE" "$DEST" || return 6
  fi
  # A unique attempt prevents an older worker with the SAME content from acknowledging a
  # later reload (A -> B pending -> A). Content hashes alone do not prove parse completion.
  NONCE=$(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')
  printf '%s' "$NONCE" | grep -Eq '^[0-9a-f]{32}$' || return 6
  MARKER=$RUN/attempts/$NONCE.conf
  cat > "$MARKER" <<EOF || return 6
server {
    listen 127.0.0.1:19091;
    server_name localhost;
    access_log off;
    location = /__ocd_generation { return 200 "$NONCE $REPLY"; }
    location / { return 404; }
}
EOF
  [ -f "$MARKER" ] || return 6
  # nginx -t has not run yet: keep the last target, so a refused config does not stay current.
  PREVIOUS=$(cat "$RUN/current.conf" 2> /dev/null) || PREVIOUS=
  printf 'include %s/servers.conf;\ninclude %s;\n' "$DEST" "$MARKER" > "$RUN/current.conf.new" \
    && mv -f "$RUN/current.conf.new" "$RUN/current.conf" || return 6
}

restore() {
  if [ -n "$PREVIOUS" ]; then
    printf '%s\n' "$PREVIOUS" > "$RUN/current.conf.restore" && mv -f "$RUN/current.conf.restore" "$RUN/current.conf"
  else
    rm -f "$RUN/current.conf"
  fi
}

# What workers load: set when front starts on current.conf and when a worker acknowledges it.
# current.conf alone can name a generation nobody loaded yet (exit 7), so cleanup keeps both.
record_loaded() {
  printf 'include %s/servers.conf;\ninclude %s;\n' "$DEST" "$MARKER" > "$RUN/loaded.conf.new" && mv -f "$RUN/loaded.conf.new" "$RUN/loaded.conf"
}

case "${1:-}" in
  --check) SERVERS=$GEN/servers.conf; AUTH=$GEN/synapse-auth.conf; check; exit $? ;;
  --start|"") ;;
  *) log "usage: front-reload [--check | --start]"; exit 2 ;;
esac

mkdir -p "$RUN/generations" "$RUN/attempts" || exit 6
# Host callers also hold the Synapse lock. This bounds direct or overlapping container calls.
# Keep the descriptor open through acknowledgement; the kernel releases it even on SIGKILL.
# Never remove the lock file: a new inode could let overlapping callers acquire separate locks.
exec 9>"$RUN/reload.lock" || exit 6
flock -n 9 || { log "another reload is running"; exit 8; }
# Failed or killed attempts leave markers, generations and stage folders (cleanup otherwise runs only
# after an acknowledgement). Under the lock, drop those older than ten minutes, long past any parse a
# signal could have started, and keep what current.conf and loaded.conf name.
KEEP=$(cat "$RUN/current.conf" "$RUN/loaded.conf" 2> /dev/null; true)
for old in "$RUN"/attempts/*.conf "$RUN"/generations/* "$RUN"/generations/.stage.*; do
  [ -e "$old" ] || continue
  case "$KEEP" in *"$old/"* | *"$old;"*) continue ;; esac
  [ -n "$(find "$old" -maxdepth 0 -mmin +10 2> /dev/null)" ] && rm -rf "$old"
done
STAGE=$(mktemp -d "$RUN/generations/.stage.XXXXXX") || exit 6
trap 'rm -rf "$STAGE"' EXIT
snapshot || exit $?
[ "${1:-}" = --start ] && { record_loaded || exit 6; exit 0; }
# nginx's own messages may quote config text: never pass them on.
if ! nginx -t -q > /dev/null 2>&1; then
  # The marker goes only once current.conf no longer names it.
  if restore; then
    rm -f "$MARKER"
    log "nginx -t refused the config; kept the last one; not reloading"
  else
    log "nginx -t refused the config and the last target could not be restored; not reloading"
  fi
  exit 4
fi
nginx -s reload > /dev/null 2>&1 || { log "nginx -s reload failed"; exit 5; }
deadline=$(( $(date +%s) + ACK_SECONDS ))
while [ "$(date +%s)" -lt "$deadline" ]; do
  loaded=$(wget -q -T 1 -O - "$LIVE_URL" 2>/dev/null) || loaded=""
  if [ "$loaded" = "$NONCE $REPLY" ]; then
    # The master parses serially. A worker serving this marker proves all earlier parses ended;
    # old workers keep parsed values in memory, not open configuration includes. If the loaded
    # record cannot be written, keep everything: the next run's age-based cleanup still bounds it.
    if record_loaded; then
      for old in "$RUN"/generations/*; do
        [ "$old" = "$DEST" ] || [ ! -d "$old" ] || rm -rf "$old"
      done
      for old in "$RUN"/attempts/*.conf; do
        [ "$old" = "$MARKER" ] || [ ! -f "$old" ] || rm -f "$old"
      done
    fi
    log "reloaded"
    exit 0
  fi
  sleep 0.1
done
log "the worker did not acknowledge the new generation; reload not verified"
exit 7
