#!/bin/sh
# Copy, then check: nginx only parses immutable front-local generations. Host writes after this
# command returns (including after a timeout) cannot change a configuration already signalled.
# A signal is not an acknowledgement. Only a fresh loopback request served by the requested
# generation proves a worker loaded it. The endpoint returns hashes only, never a credential.
# Exit codes: 3 files changed/invalid; 4 config test failed (the last current.conf is kept);
# 5 signal failed; 6 snapshot failure; 7 acknowledgement timed out; 8 another local reload is
# running; 2 usage.
set -u
umask 077

GEN=${OCD_FRONT_GEN:-/etc/nginx/front-gen}
RUN=${OCD_FRONT_RUN:-/tmp/front}
HEADER='# Generated by the bridge (src/synapse/auth-conf.ts). One variable only. Do not edit.'
MAX_BYTES=3925
LIVE_URL=http://127.0.0.1:19091/__ocd_generation
PREVIOUS=

log() { printf 'front-reload: %s\n' "$*" >&2; }

check() {
  [ -n "${OCD_FRONT_HASH:-}" ] || { log "OCD_FRONT_HASH is not set; not reloading"; return 3; }
  SERVERS_SHA=$(sha256sum "$SERVERS" 2> /dev/null | cut -d' ' -f1)
  [ "$SERVERS_SHA" = "$OCD_FRONT_HASH" ] || { log "servers.conf is not the file front started with (OCD_FRONT_HASH); not reloading (restart the sandbox through the bridge)"; return 3; }
  [ -f "$AUTH" ] || { log "synapse-auth.conf is missing; not reloading"; return 3; }
  bytes=$(wc -c < "$AUTH" | tr -d ' ')
  [ "$bytes" -le "$MAX_BYTES" ] || { log "synapse-auth.conf is longer than the bridge ever writes; not reloading"; return 3; }
  others=$(LC_ALL=C tr -d 'A-Za-z0-9 #()/._$";\n-' < "$AUTH" | wc -c | tr -d ' ')
  [ "$others" = 0 ] || { log "synapse-auth.conf has characters the bridge never writes; not reloading"; return 3; }
  newlines=$(wc -l < "$AUTH" | tr -d ' ')
  records=$(awk 'END { print NR }' "$AUTH")
  [ "$newlines" = 2 ] && [ "$records" = 2 ] || { log "synapse-auth.conf is not exactly two lines; not reloading"; return 3; }
  [ "$(sed -n 1p "$AUTH")" = "$HEADER" ] || { log "synapse-auth.conf header is not the bridge's; not reloading"; return 3; }
  sed -n 2p "$AUTH" | grep -Eqx 'set \$synapse_auth "(Bearer [A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,})?";' \
    || { log "synapse-auth.conf does not set only \$synapse_auth to \"\" or a bearer token; not reloading"; return 3; }
  AUTH_SHA=$(sha256sum "$AUTH" | cut -d' ' -f1)
}

snapshot() {
  cp "$GEN/servers.conf" "$STAGE/source-servers.conf" && cp "$GEN/synapse-auth.conf" "$STAGE/synapse-auth.conf" \
    || { log "could not copy the generated files"; return 3; }
  SERVERS=$STAGE/source-servers.conf
  AUTH=$STAGE/synapse-auth.conf
  check || return $?
  GENERATION=$SERVERS_SHA-$AUTH_SHA
  DEST=$RUN/generations/$GENERATION
  # Every include names this immutable generation, never a mutable 'current' directory.
  sed "s|include /etc/nginx/front-gen/synapse-auth\.conf;|include $DEST/synapse-auth.conf;|g" "$SERVERS" > "$STAGE/servers.conf" || return 6
  # Retries reuse the same content-addressed generation. Never overwrite a file nginx may read.
  if [ -d "$DEST" ]; then
    cmp -s "$STAGE/source-servers.conf" "$DEST/source-servers.conf" \
      && cmp -s "$STAGE/synapse-auth.conf" "$DEST/synapse-auth.conf" \
      && cmp -s "$STAGE/servers.conf" "$DEST/servers.conf" \
      || { log "the existing generation differs from its content hash"; return 6; }
  else
    mv "$STAGE" "$DEST" || return 6
  fi
  # A unique attempt prevents an older worker with the SAME content from acknowledging a
  # later reload (A -> B pending -> A). Content hashes alone do not prove parse completion.
  NONCE=$(od -An -N16 -tx1 /dev/urandom | tr -d ' \n')
  printf '%s' "$NONCE" | grep -Eq '^[0-9a-f]{32}$' || return 6
  MARKER=$RUN/attempts/$NONCE.conf
  cat > "$MARKER" <<EOF || return 6
server {
    listen 127.0.0.1:19091;
    server_name localhost;
    access_log off;
    location = /__ocd_generation { return 200 "$NONCE $SERVERS_SHA $AUTH_SHA"; }
    location / { return 404; }
}
EOF
  [ -f "$MARKER" ] || return 6
  # nginx -t has not run yet: keep the last target, so a refused config does not stay current.
  PREVIOUS=$(cat "$RUN/current.conf" 2> /dev/null) || PREVIOUS=
  printf 'include %s/servers.conf;\ninclude %s;\n' "$DEST" "$MARKER" > "$RUN/current.conf.new" \
    && mv -f "$RUN/current.conf.new" "$RUN/current.conf" || return 6
}

restore() {
  if [ -n "$PREVIOUS" ]; then
    printf '%s\n' "$PREVIOUS" > "$RUN/current.conf.new" && mv -f "$RUN/current.conf.new" "$RUN/current.conf"
  else
    rm -f "$RUN/current.conf"
  fi
}

case "${1:-}" in
  --check) SERVERS=$GEN/servers.conf; AUTH=$GEN/synapse-auth.conf; check; exit $? ;;
  --start|"") ;;
  *) log "usage: front-reload [--check | --start]"; exit 2 ;;
esac

mkdir -p "$RUN/generations" "$RUN/attempts" || exit 6
# Host callers also hold the Synapse lock. This bounds direct or overlapping container calls.
# Keep the descriptor open through acknowledgement; the kernel releases it even on SIGKILL.
# Never remove the lock file: a new inode could let overlapping callers acquire separate locks.
exec 9>"$RUN/reload.lock" || exit 6
flock -n 9 || { log "another reload is running"; exit 8; }
STAGE=$(mktemp -d "$RUN/generations/.stage.XXXXXX") || exit 6
trap 'rm -rf "$STAGE"' EXIT
snapshot || exit $?
[ "${1:-}" = --start ] && exit 0
# nginx's own messages may quote config text: never pass them on.
nginx -t -q > /dev/null 2>&1 || { restore; log "nginx -t refused the config; kept the last one; not reloading"; exit 4; }
nginx -s reload > /dev/null 2>&1 || { log "nginx -s reload failed"; exit 5; }
deadline=$(( $(date +%s) + 20 ))
while [ "$(date +%s)" -lt "$deadline" ]; do
  loaded=$(wget -q -T 1 -O - "$LIVE_URL" 2>/dev/null) || loaded=""
  if [ "$loaded" = "$NONCE $SERVERS_SHA $AUTH_SHA" ]; then
    # The master parses serially. A worker serving this marker proves all earlier parses ended;
    # old workers keep parsed values in memory, not open configuration includes.
    for old in "$RUN"/generations/*; do
      [ "$old" = "$DEST" ] || [ ! -d "$old" ] || rm -rf "$old"
    done
    for old in "$RUN"/attempts/*.conf; do
      [ "$old" = "$MARKER" ] || [ ! -f "$old" ] || rm -f "$old"
    done
    log "reloaded"
    exit 0
  fi
  sleep 0.1
done
log "the worker did not acknowledge the new generation; reload not verified"
exit 7
