#!/bin/sh
# front-reload (review M1 of 90434eaaf5): the ONLY way the bridge reloads front's nginx
# (src/synapse/token-manager.ts reloadFront, via `docker exec <front> /usr/local/bin/front-reload`).
# A plain `nginx -s reload` would load whatever is in the read-only generated folder now. If the
# bridge wrote a new servers.conf and `compose up` then failed, the old front would load the new,
# unchecked file on the next token reload. So, before nginx even tests the config:
# 1. servers.conf must have the sha256 front was started with (OCD_FRONT_HASH, its front-config label);
# 2. synapse-auth.conf must be the strict one-variable file (src/synapse/auth-conf.ts AUTH_CONF_SHAPE):
#    the header line, then `set $synapse_auth "";` or `set $synapse_auth "Bearer <JWT>";`, nothing else.
# Only then `nginx -t`, and only if that passes, `nginx -s reload`.
# `front-reload --check` runs checks 1 and 2 only (the entrypoint calls it before nginx starts).
# Exit codes: 0 reloaded (or checks passed); 3 the generated files are not the ones front started
# with or not the strict shape (nothing reloaded); 4 nginx -t refused (nothing reloaded);
# 5 nginx -s reload failed; 2 usage. It never prints the include (it may hold the owner's token).
set -u

GEN=${OCD_FRONT_GEN:-/etc/nginx/front-gen}
SERVERS=$GEN/servers.conf
AUTH=$GEN/synapse-auth.conf
HEADER='# Generated by the bridge (src/synapse/auth-conf.ts). One variable only. Do not edit.'
# The bridge's own limit (isAuthConf): the header, a token of at most 3800 characters, and 40 more.
MAX_BYTES=3925

log() { printf 'front-reload: %s\n' "$*" >&2; }

check() {
  [ -n "${OCD_FRONT_HASH:-}" ] || { log "OCD_FRONT_HASH is not set; not reloading"; return 3; }
  actual=$(sha256sum "$SERVERS" 2> /dev/null | cut -d' ' -f1)
  [ "$actual" = "$OCD_FRONT_HASH" ] || { log "servers.conf is not the file front started with (OCD_FRONT_HASH); not reloading (restart the sandbox through the bridge)"; return 3; }
  [ -f "$AUTH" ] || { log "synapse-auth.conf is missing; not reloading"; return 3; }
  bytes=$(wc -c < "$AUTH" | tr -d ' ')
  [ "$bytes" -le "$MAX_BYTES" ] || { log "synapse-auth.conf is longer than the bridge ever writes; not reloading"; return 3; }
  # Byte allowlist first (no CR, tab, NUL or anything else the bridge never writes), whatever
  # line handling the tools below have.
  others=$(LC_ALL=C tr -d 'A-Za-z0-9 #()/._$";\n-' < "$AUTH" | wc -c | tr -d ' ')
  [ "$others" = 0 ] || { log "synapse-auth.conf has characters the bridge never writes; not reloading"; return 3; }
  # Exactly two lines, each ended by a newline (wc counts newlines, awk also counts a last partial line).
  newlines=$(wc -l < "$AUTH" | tr -d ' ')
  records=$(awk 'END { print NR }' "$AUTH")
  [ "$newlines" = 2 ] && [ "$records" = 2 ] || { log "synapse-auth.conf is not exactly two lines; not reloading"; return 3; }
  [ "$(sed -n 1p "$AUTH")" = "$HEADER" ] || { log "synapse-auth.conf header is not the bridge's; not reloading"; return 3; }
  # The token's three base64url parts; their lengths are bounded by MAX_BYTES above (musl's regex
  # caps a repeat count at 255, so the bridge's per-part limits are not repeated here).
  sed -n 2p "$AUTH" | grep -Eqx 'set \$synapse_auth "(Bearer [A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,})?";' \
    || { log "synapse-auth.conf does not set only \$synapse_auth to \"\" or a bearer token; not reloading"; return 3; }
  return 0
}

case "${1:-}" in
  --check) check; exit $? ;;
  "") ;;
  *) log "usage: front-reload [--check]"; exit 2 ;;
esac

check || exit $?
# nginx's own messages can quote config text; they are not passed on.
nginx -t -q > /dev/null 2>&1 || { log "nginx -t refused the config; not reloading (front keeps the last good one)"; exit 4; }
nginx -s reload > /dev/null 2>&1 || { log "nginx -s reload failed"; exit 5; }
log "reloaded"
exit 0
